server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    url: jdbc:p6spy:mysql://127.0.0.1:3306/practice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  #redis
  redis:
    database: 1
    host: 192.168.18.132
    pool: 6379
    password: root
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1
    timeout: 50000
#mybatis
mybatis:
  #type-aliases-package: com.agri.study.wen.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  executor-type: reuse
  configuration:
    map-underscore-to-camel-case: true #驼峰命名开启
